CITY_NUM = {
	"Taipei": "1",
	"New_Taipei": "3"
}
SECTION_NUM = {
	"Zhongzheng": "1",
	"Datong": "2",
	"Zhongshan": "3",
	"Songshan": "4",
	"Daan": "5",
	"Wanhua": "6",	
	"Xinyi": "7",
	"Shilin": "8",
	"Beitou": "9",
	"Neihu": "10",
	"Nangang": "11",
	"Wenshan": "12",
	"Wanli": "20",
	"Jinshan": "21",
	"Banqiao": "26",
	"Xizhi": "27",
	"Shenkeng": "28",
	"Shiding": "29",
	"Ruifang": "30",
	"Pingxi": "31",
	"Shuangxi": "32",
	"Gongliao": "33",
	"Xindian": "34",
	"Pinglin": "35",
	"Wulai": "36",
	"Yonghe": "37",
	"Zhonghe": "38",
	"Tucheng": "39",
	"Sanxia": "40",
	"Shulin": "41",
	"Yingge": "42",
	"Sanchong": "43",
	"Xinzhuang": "44",
	"Taishan": "45",
	"Linkou": "46",
	"Luzhou": "47",
	"Wugu": "48",
	"Bali": "49", 
	"Tamsui": "50",
	"Sanzhi": "51",
	"Shimen": "52"
} 	